#! /usr/bin/env python

# Panflute
# Copyright (C) 2010 Paul Kuliniewicz <paul@kuliniewicz.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02111-1301, USA.

from __future__ import absolute_import

import panflute.debugger
import panflute.util

import dbus.mainloop.glib
import gtk


if __name__ == "__main__":
    panflute.util.init_i18n ()
    dbus.mainloop.glib.DBusGMainLoop (set_as_default = True)

    debugger = panflute.debugger.create_debugger ()
    debugger.show ()
    gtk.main ()
